version: '3'
services:
  nginx:
    image: 'nginx:mainline-alpine'
    ports:
      - '80:80'
    networks:
      - 'eggjs-network'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './site.conf:/etc/nginx/sites-enabled/site.conf'
  eggjs:
    image: 'hub.tencentyun.com/muchen/eggjs:0.0.1'
    ports:
      - '7001:7001'
    networks:
      - 'eggjs-network'
networks:
  eggjs-network:      
  